# labeler "full" schema

# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true
# comments object allows you to specify a different message for issues and prs

comments:
  issues: |
    Thanks for opening this issue!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.
  prs: |
    Thanks for the contribution!
    I have applied any labels matching special text in your title and description.

    Please review the labels and make any necessary changes.

# Labels is an object where:
# - keys are labels
# - values are objects of { include: [ pattern ], exclude: [ pattern ] }
#    - pattern must be a valid regex, and is applied globally to
#      title + description of issues and/or prs (see enabled config above)
#    - 'include' patterns will associate a label if any of these patterns match
#    - 'exclude' patterns will ignore this label if any of these patterns match
#    - 'branches' is an optional array of branch names (or patterns) to limit labeling according to PR target branch
labels:
  '♻️ refactor':
    include:
      - '\brefactor[s]?\b'
    exclude: []
  '✅ test':
    include:
      - '\btest[s]?\b'
    exclude: []
  '✨ feat':
    include:
      - '\bfeat\b'
    exclude: []
  '🎨 style':
    include:
      - '\bstyle[s]?\b'
    exclude: []
  '🐛 fix':
    include:
      - '\bfix[es]?\b'
    exclude: []
  '💄 design':
    include:
      - '\bdesign[s]?\b'
    exclude: []
  '💬 comment':
    include:
      - '\bcomment[s]?\b'
    exclude: []
  '📝 docs':
    include:
      - '\bdoc[s]?\b'
    exclude: []
  '🔥 remove':
    include:
      - '\bremove[s]?\b'
    exclude: []
  '🔧 chore':
    include:
      - '\bchore[s]?\b'
    exclude: []
  '🚑 HOTFIX':
    include:
      - '\bHOTFIX\b'
    exclude: []
  '🚚 rename':
    include:
      - '\brename\b'
    exclude: []
