export { http, ApiError, type RequestOptions } from '@/shared/api/http'
export * as authApi from '@/shared/api/auth'
export * as regionApi from '@/shared/api/region'
export * as userApi from '@/shared/api/user'
export * as diagnosisApi from '@/shared/api/diagnosis'
export * as roadmapApi from '@/shared/api/roadmap'
export * as homeApi from '@/shared/api/home'
export * as fundApi from '@/shared/api/fund'
export * as expenseApi from '@/shared/api/expense'
